In [5]:
# Python program to count the frequency of
# elements in a list using a dictionary
 
def CountFrequency(my_list):
 
    # Creating an empty dictionary
    freq = {}
    for item in my_list:
        if (item in freq):
            freq[item] += 1
        else:
            freq[item] = 1
 
    # for key, value in freq.items():
    #     print ("% d : % d"%(key, value))
    return freq
 
# Driver function

my_list =[1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2]

sample = CountFrequency(my_list)

In [6]:
sample

{1: 5, 5: 2, 3: 3, 4: 3, 2: 4}

In [47]:
import numpy as np
sampleMin = 3
my_list =[1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2]
keys_list, values_list = np.unique(my_list, return_counts=True)

In [25]:
def sample_min(values_list, sample_size=1):
    # sample = []
    return [min(x, sample_size) for x in values_list]
        
    # return sample

In [45]:
import numpy as np
input_a = 3
input_b = np.array([1,2,3,4,5])

input_b[input_b > input_a] = input_a

print(input_b)

[1 2 3 3 3]


In [48]:
values_list

array([5, 4, 3, 3, 2], dtype=int64)

In [49]:
values_list[values_list > sampleMin] = sampleMin


In [50]:
values_list

array([3, 3, 3, 3, 2], dtype=int64)

In [51]:
zip_iterator = zip(keys_list, values_list)
a_dictionary = dict(zip_iterator)

In [52]:
a_dictionary

{1: 3, 2: 3, 3: 3, 4: 3, 5: 2}

In [ ]:
sample_params = { 1: min(SAMPLE, 1468136),
                  2: min(SAMPLE, 2262087),
                  3: min(SAMPLE, 195712),
                  4: min(SAMPLE, 377),
                  5: min(SAMPLE, 1),
                  6: min(SAMPLE, 11426),
                  7: min(SAMPLE, 62261)}

In [3]:
import numpy as np
from scipy import stats
a = np.array([[1, 3, 4, 2, 2, 7],
              [5, 2, 2, 1, 4, 1],
              [3, 3, 2, 2, 1, 1]])

In [4]:
a.shape

(3, 6)

In [5]:
m = stats.mode(a)
print(m)

ModeResult(mode=array([[1, 3, 2, 2, 1, 1]]), count=array([[1, 2, 2, 2, 1, 2]]))


In [6]:
m[0][0]

array([1, 3, 2, 2, 1, 1])